# Generated by Django 2.2.6 on 2020-05-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compType', models.IntegerField(blank=True, choices=[(0, 'Üniversiteler Arası'), (1, 'Okullar Arası'), (2, 'Ferdi')], db_column='compType', null=True)),
                ('compGeneralType', models.IntegerField(blank=True, choices=[(0, 'Türkiye'), (1, 'Dünya'), (2, 'Olimpiyat'), (3, 'Avrupa')], db_column='compGeneralType', null=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'YURT İÇİ FAALİYETLERİ'), (1, 'YURT DIŞI FAALİYETLERİ'), (2, 'EGİTİM FAALİYETLERİ')], db_column='Type', null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True, db_column='creationDate', null=True)),
                ('operationDate', models.DateTimeField(auto_now_add=True, db_column='operationDate', null=True)),
                ('startDate', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('finishDate', models.DateTimeField(blank=True, db_column='finishDate', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('eventPlace', models.CharField(blank=True, db_column='eventPlace', max_length=45, null=True)),
                ('eventDate', models.CharField(blank=True, db_column='eventDate', max_length=45, null=True)),
                ('isOpen', models.BooleanField(db_column='isOpen', default=False)),
                ('registerStartDate', models.DateTimeField(blank=True, db_column='registerStartDate', null=True)),
                ('registerFinishDate', models.DateTimeField(blank=True, db_column='registerFinishDate', null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
