# Generated by Django 2.2.6 on 2020-05-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceReferee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[('Onaylandı', 'Onaylandı'), ('Onaya Gönderildi', 'Onaya Gönderildi'),
                             ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')], default='Beklemede',
                    max_length=128, verbose_name='Onay Durumu')),
                ('iban', models.CharField(blank=True, max_length=120, null=True, verbose_name='İban Adresi')),
                ('tc', models.CharField(blank=True, max_length=120, null=True)),
                ('height', models.CharField(blank=True, max_length=120, null=True)),
                ('weight', models.CharField(blank=True, max_length=120, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=120, null=True, verbose_name='Doğum Yeri')),
                ('motherName', models.CharField(blank=True, max_length=120, null=True, verbose_name='Anne Adı')),
                ('fatherName', models.CharField(blank=True, max_length=120, null=True, verbose_name='Baba Adı')),
                ('profileImage',
                 models.ImageField(blank=True, default='profile/user.png', null=True, upload_to='profile/',
                                   verbose_name='Profil Resmi')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('bloodType', models.CharField(
                    choices=[('AB Rh+', 'AB Rh+'), ('AB Rh-', 'AB Rh-'), ('A Rh+', 'A Rh+'), ('A Rh-', 'A Rh-'),
                             ('B Rh+', 'B Rh+'), ('B Rh-', 'B Rh-'), ('AB Rh+', '0 Rh+'), ('AB Rh+', '0 Rh-')],
                    default='AB Rh+', max_length=128, verbose_name='Kan Grubu')),
                ('gender',
                 models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='Erkek', max_length=128,
                                  verbose_name='Cinsiyeti')),
                ('postalCode', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('city',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_city', to='sbs.City',
                                   verbose_name='İl')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_country',
                                              to='sbs.Country', verbose_name='Ülke')),
            ],
        ),
    ]
